version: "3.8"
services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: mcscanner
      POSTGRES_PASSWORD: mcscannerpass
      POSTGRES_DB: mcdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mcscanner -d mcdata -q"]
      interval: 5s
      timeout: 5s
      retries: 10

  controller:
    build: .
    container_name: controller
    command: python controller/main.py
    env_file: .env
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

  dashboard:
    build: .
    container_name: dashboard
    command: python controller/dashboard.py
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

  worker:
    build: .
    command: celery -A worker.worker:app worker --pool=eventlet --concurrency=100
    env_file: .env
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

volumes:
  pgdata:
